# Generated by Django 2.1.5 on 2019-04-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': "SignUp's"},
        ),
    ]
